apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-service-account
  namespace: gitea
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gitea
  name: gitea-role
rules:
- apiGroups: [""]  # "" indicates the core API group
  resources: ["pods", "pods/exec", "namespaces"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: ["apps.openshift.io"]
  resources: ["deploymentconfigs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings", "roles"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: ["helm.openshift.io"]
  resources: ["helmreleases"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-role-binding
subjects:
- kind: ServiceAccount
  name: gitea-service-account
  namespace: gitea
roleRef:
  kind: Role
  name: gitea-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: gitea-install-job
  namespace: gitea
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: gitea-service-account
      containers:
      - name: gitea-installer
        image: ghcr.io/lucifergene/gitea-installer-openshift:main